# Project information
site_name: "flet-flashlight"
site_url: https://flet-dev.github.io/flet-flashlight/
site_author: Flet Contributors
site_description: A Flet extension to manage the device torch/flashlight.

# Repository
edit_uri: edit/main/docs/
repo_name: flet-dev/flet-flashlight
repo_url: https://github.com/flet-dev/flet-flashlight

# Copyright
copyright: Copyright &copy; 2025 Flet Contributors

# Theme
theme:
  name: "material"
  favicon: 'images/favicon.ico'
  logo: 'images/logo.svg'
  icon:
    annotation: material/plus-circle
  palette:
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
  features:
    - content.action.edit
    - content.action.view
    - content.action.annotate
    - content.action.copy
    - content.tooltips
    - content.action.tooltips
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    # - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.footer
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/flet-dev
    - icon: fontawesome/brands/discord
      link: https://discord.gg/bCFXYgZR3b
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/fletdev
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/fletdev.bsky.social

# Navigation
nav:
  - Getting Started: index.md
  - API Reference:
      - Flashlight: flashlight.md
      - FlashlightException:
          - exceptions/flashlight_exception.md
          - FlashlightDisableException: exceptions/flashlight_disable_exception.md
          - FlashlightDisableExistentUserException: exceptions/flashlight_disable_existent_user_exception.md
          - FlashlightDisableNotAvailableException: exceptions/flashlight_disable_not_available_exception.md
          - FlashlightEnableExistentUserException: exceptions/flashlight_enable_existent_user_exception.md
          - FlashlightEnableException: exceptions/flashlight_enable_exception.md
          - FlashlightEnableNotAvailableException: exceptions/flashlight_enable_not_available_exception.md
  - Changelog: changelog.md
  - License: license.md

# Validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

# Watch
watch:
  - docs
  - src/flet_flashlight
  - CHANGELOG.md
  - LICENSE
  - README.md

# Plugins
plugins:
  # - footnotes
  - search:
      lang: en
  - open-in-new-tab
  - mike:
      alias_type: symlink
  - glightbox
  - section-index
  - external-images:
      mappings:
        - source_dir: examples
          target_url_path: examples
          include_exts: [ ".png", ".gif", ".svg" ]
  - mkdocstrings:
      default_handler: python_xref
      handlers:
        python_xref:
          options:
            relative_crossrefs: true
            docstring_style: google
            show_signature_annotations: true
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_heading: true
            show_root_full_path: false
            show_bases: true
            show_source: false
            group_by_category: true
            show_category_heading: false
            show_labels: false
            show_if_no_docstring: true
            docstring_section_style: spacy
            separate_signature: true
            inherited_members: true
            preload_modules: [ flet ]
            filters:
              - "!^_"   # Exclude private members starting with only one underscore
            extensions:
              - griffe_modernized_annotations
              - griffe_warnings_deprecated
          inventories:
            - url: https://docs.flet.dev/objects.inv
            - url: https://docs.python.org/3/objects.inv
              domains: [ py, std ]
            - url: https://typing-extensions.readthedocs.io/en/latest/objects.inv

# Markdown Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: "#"

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.magiclink:
      repo_url_shorthand: true
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.blocks.caption
