name: flet_flashlight
description: Flet Flashlight control
homepage: https://flet.dev
repository: https://github.com/flet-dev/flet-flashlight/src/flutter/flet_flashlight
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


  collection: ^1.16.0
  torch_light: ^1.1.0

  flet: ^0.25.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0