name: docs

on:
  push:
    branches:
      - main
    paths:
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'pyproject.toml'
      - '.github/workflows/docs.yml'
      - 'src/flet_flashlight/**'
      - 'examples/flashlight_example/src/**'

  workflow_dispatch:    # Allow manual trigger from the GitHub Actions UI

concurrency:
  group: "docs"                   # Prevent multiple overlapping deploys
  cancel-in-progress: false       # Allow in-progress deploys to finish

permissions:
  contents: write  # Required to push to the gh-pages branch

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}         # Token used by mkdocs for pushing
  UV_SYSTEM_PYTHON: 1                       # Use system Python interpreter with uv

jobs:
  deploy:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    if: github.repository == github.event.repository.full_name  # don't run on forks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git for mkdocs
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"  # Match Python version with project config

      - name: Install dependencies
        run: |
          uv pip install -e .
          uv pip install --group docs --group lint

      - name: Deploy to GitHub Pages
        run: uv run mkdocs gh-deploy --force
